노민하 / 주중8B / 1주차
devyuriii/Algorithm-Tear-Up pull request #356
Opened 2022-11-01 10:54 UTC by MinaRoh

2022-11-06 03:28 UTC, kkdy21 reviewed
수고하셨습니다~~

2022-11-06 03:33 UTC, kkdy21 requested changes, later dismissed
.

2022-11-06 03:39 UTC, kkdy21 commented on 주중8B/Minha/Week1/소수 찾기.js
> +      for (let i = 2; i <= Math.sqrt(n); i++) {
저도 제곱근으로 풀었는데 +2증가하는 로직으로 푸니 시간이좀더 잘나왔던것 같습니다~~

2022-11-06 03:41 UTC, kkdy21 commented on 주중8B/Minha/Week1/폰켓몬.js
> +        if(!arr.includes(nums[i]) && arr.length < nums.length / 2)
arr.length < nums.length / 2 조건이 좋은것같네요~!

2022-11-06 03:42 UTC, kkdy21 commented on 주중8B/Minha/Week1/최댓값과 최솟값.js
> +    return `${splitted[0]} ${splitted[splitted.length-1]}`;
저랑 푼게 너무비슷해서 놀랐어요~~

2022-11-06 03:45 UTC, kkdy21 commented on 주중8B/Minha/Week1/JadenCase 문자열.js
> +        answer += el.charAt(0).toUpperCase() + el.slice(1) + " ";
slice에서 "begin이 배열의 길이보다 큰 경우에는, 빈 배열을 반환합니다." 를 잘활용하신것같아요!

2022-11-06 03:50 UTC, kkdy21 commented
> .

.

2022-11-14 15:56 UTC, merged

2022-11-15 11:11 UTC, callmejeje commented on 주중8B/Minha/Week2/소수 만들기.js
> +    }
저랑 비슷하게 3중 for문으로 푸셨군요..!

2022-11-15 11:11 UTC, callmejeje commented on 주중8B/Minha/Week2/올바른 괄호.js
> +    }
하나의 변수로 처리한게 정말 깔끔하시네요!

2022-11-15 11:11 UTC, callmejeje commented on 주중8B/Minha/Week2/최솟값 만들기.js
> +    let sortedB = B.sort((a,b)=>b-a) // 내림차순으로 정렬 4321
이 변수들은 안 쓰인 것 같네요..!?

2022-11-15 11:11 UTC, callmejeje commented on 주중8B/Minha/Week2/실패율.js
> +        let staying = stages.filter(n => n === i).length;
filter 사용하니 깔끔하네요!